language: java

jdk:
- openjdk8

stages:
- compile
- test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: compile
    script: ./gradlew assemble
  - stage: test
    script: ./gradlew test
  - stage: deploy
    script: ./gradlew bintrayUpload

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/